import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ContenstStackLivePreviewInit } from "@/contentstack/ContentstackLivePreviewInit";
import { stack } from "@/contentstack/sdk";
import { Debug } from "@/components/Debug";
import { LivePreviewQuery } from "@contentstack/delivery-sdk";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = await stack
    .contentType("alert_ribbon")
    .entry("blt0f2f57593882239c")
    .fetch<{
      title: string;
      show: boolean;
    }>();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContenstStackLivePreviewInit />
        {content.show && (
          <div className="bg-yellow-100 w-full p-1">{content.title}</div>
        )}
        {children}
      </body>
    </html>
  );
}
